Tempo (min) = 

SUMX(
    FILTER(
        FatoOrdemProduzida,
        NOT ISBLANK(FatoOrdemProduzida[dataInicioProd]) &&
        NOT ISBLANK(FatoOrdemProduzida[dataFimProd])
    ),
    DATEDIFF(
        FatoOrdemProduzida[dataInicioProd],
        FatoOrdemProduzida[dataFimProd],
        MINUTE
    )
)