Valor Produzido p/Min = 

VAR MinutosTotais =
    SUMX(
        FatoOrdemProduzida,
        DATEDIFF(
            FatoOrdemProduzida[dataInicioProd],
            FatoOrdemProduzida[dataFimProd],
            MINUTE
        )
    )
RETURN
DIVIDE([Valor Produzido], MinutosTotais)
